=== maxpushkarev/3DEngine/JaxbTask1/schema/scene.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scene.xsd">
	<xs:element name="scene">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="points" type="points" minOccurs="1" maxOccurs="1"/>
				<xs:element name="faces" type="faces" minOccurs="1" maxOccurs="1"/>
				<xs:element name="objects" type="objects" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="point-id">
			<xs:selector xpath="points/point"/>
			<xs:field xpath="id"/>
		</xs:key>
		<xs:key name="face-id">
			<xs:selector xpath="faces/face"/>
			<xs:field xpath="id"/>
		</xs:key>
		<xs:unique name="object-name">
			<xs:selector xpath="objects/object"/>
			<xs:field xpath="name"/>
		</xs:unique>
		<xs:keyref name="face-point" refer="point-id">
			<xs:selector xpath="faces/face/point-id"/>
			<xs:field xpath="."/>
		</xs:keyref>
		<xs:keyref name="object-face" refer="face-id">
			<xs:selector xpath="objects/object/face-id"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
	<xs:complexType name="points">
		<xs:sequence>
			<xs:element name="point" type="point" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="point">
		<xs:sequence>
			<xs:element name="id" type="xs:int" minOccurs="1" maxOccurs="1"/>
			<xs:element name="x" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="y" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="z" type="xs:double" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="faces">
		<xs:sequence>
			<xs:element name="face" type="face" minOccurs="0" maxOccurs="unbounded">
				<xs:unique name="points-inside-face">
					<xs:selector xpath="point-id"/>
					<xs:field xpath="."/>
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="face">
		<xs:sequence>
			<xs:element name="id" type="xs:int"/>
			<xs:element name="point-id" type="xs:int" minOccurs="3" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="objects">
		<xs:sequence>
			<xs:element name="object" type="object" minOccurs="0" maxOccurs="unbounded">
				<xs:unique name="faces-in-object">
					<xs:selector xpath="face-id"/>
					<xs:field xpath="."/>
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="object">
		<xs:sequence>
			<xs:element name="name" minOccurs="1" maxOccurs="1">
				<xs:simpleType xml:base="xs:string">
					<xs:restriction base="xs:string">
						<xs:minLength value="1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="face-id" type="xs:int" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== maxpushkarev/3DEngine/Task1Scene/target/example.xml
<?xml version="1.0" encoding="utf-8"?>
<scene xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scene.xsd">
	<points>
		<point>
			<id>1</id>
			<x>-1.8</x>
			<y>-1.8</y>
			<z>0</z>
		</point>
		<point>
			<id>2</id>
			<x>1.8</x>
			<y>-1.8</y>
			<z>0</z>
		</point>
		<point>
			<id>3</id>
			<x>0</x>
			<y>1.8</y>
			<z>0</z>
		</point>
		<point>
			<id>4</id>
			<x>0</x>
			<y>0</y>
			<z>1.2</z>
		</point>
	</points>
	<faces>
		<face>
			<id>1</id>
			<point-id>1</point-id>
			<point-id>2</point-id>
			<point-id>3</point-id>
		</face>
		<face>
			<id>2</id>
			<point-id>1</point-id>
			<point-id>2</point-id>
			<point-id>4</point-id>
		</face>
		<face>
			<id>3</id>
			<point-id>1</point-id>
			<point-id>4</point-id>
			<point-id>3</point-id>
		</face>
		<face>
			<id>4</id>
			<point-id>4</point-id>
			<point-id>2</point-id>
			<point-id>3</point-id>
		</face>
	</faces>
	<objects>
		<object>
			<name>pyramid</name>
			<face-id>1</face-id>
			<face-id>2</face-id>
			<face-id>3</face-id>
			<face-id>4</face-id>
		</object>
	</objects>
</scene>
